#!/usr/bin/env perl

use strict;
use warnings;
use Net::FTP;
use Getopt::Long;
use Pod::Usage;
use Image::Magick;
use AtExit;
use Log::Any::App qw($log), -syslog => 0, -screen =>{level => 'error',
													 color => 0},
										  -file => { level => 'info',
									   	      		 path => 'electro.log'};

my $outfile = "a.gif";
my $day;
my $month;
my $year;
my $help = 0;
my $debug = 0;
my $scale = 300;

my @files = ();


sub cleanup{
	foreach my $x (@files) {
		unlink $x if $x;
	}
	rmdir "tmp";
}

sub check_date {
	my $day = shift;
	my $month = shift;
	my $year = shift;
	if($year < 2012){return 0;}
	if($month > 12 || $month < 1){return 0;}
	if($day < 1){return 0;}
	if($day > 31){return 0;}
	return 1;
}

my %months = ("01" => "January",
		   	  "02" => "February",
		      "03" => "March",
		      "04" => "April",
		      "05" => "May",
		      "06" => "June",
		      "07" => "July",
		      "08" => "August",
		      "09" => "September",
		      "10" => "October",
		      "11" => "November",
		      "12" => "December");

atexit("cleanup");

GetOptions("out|o=s" =>\$outfile,
		   "debug|d!" => \$debug,
		   "scale|s=s" => \$scale,
		   "help|h" => sub{pod2usage(2);});

$ARGV[0] =~ /(\d{2})(\d{2})(\d{4})/;
$day = $1;
$month = $2;
$year = $3;

if(!$scale =~ /^d+$/){ $scale = 300;}

$log->crit("Incorrect date format") if(!check_date($day, $month, $year));
$log->info("Start script with params:\n  date = $day $month $year\n  debug = $debug\n  output = $outfile\n  scale = $scale");

mkdir "tmp", 0775;

my $ftp = Net::FTP->new("ftp.ntsomz.ru", Debug => $debug, Passive => 1, ) or $log->crit("Can't connect to server, $@");
$log->info("Connected to ftp://ftp.ntsomz.ru");
$ftp->login("electro","electro") or $log->crit("Can't login at server ftp://ftp.ntsomz.ru");
$log->info("Logged in at ftp://ftp.ntsomz.ru as electro");

my $resftp = Net::FTP->new("ftp1.rcpod.ru", Debug => $debug, Passive => 1) or $log->crit("Can't connect to server, $@");
$log->info("Connected to ftp://ftp1.rcpod.ru");
$resftp->login() or $log->crit("Can't login at server at server ftp://ftp1.rcpod.ru");
$log->info("Logged in at ftp://ftp1.rcpod.ru");

$ftp->binary();
$resftp->binary();

$resftp->cwd("ElectroL") or $log->error("Can't find directory");

$ftp->cwd($year) or $log->error("Can't find directory $year");
$resftp->cwd($year) or $log->error("Can't find directory $year");
$ftp->cwd($months{$month}) or $log->error("Can't find directory $months{$month}");
$resftp->cwd($months{$month}) or $log->error("Can't find directory $months{$month}");
$ftp->cwd($day) or $log->error("Can't find directory $day");
$resftp->cwd($day) or $log->error("Can't find directory $day");
for (my $i = 0; $i < 48; $i++) {
	my $nextdir = ($i > 19 ? ($i - $i % 2) / 2 : "0" . ($i - $i % 2) / 2 ) . ($i % 2 ? "30" : "00" ); #generate all directories names	
	if($nextdir le "0600" || $nextdir ge "0830"){
		if($ftp->cwd($nextdir)){
			my $addr = ($year % 100) . $month . $day . "_" . $nextdir . "_RGB.jpg";
			if(my $tmp = $ftp->get($addr, "tmp\/$i.jpg")){
				$log->info("Download file $addr");
				push @files, $tmp;
			}
			else{$log->error("Can't download file $addr");}
			$ftp->cdup() or $log->error("Can't find prev directory");
		}
		else{$log->error("Can't find directory $nextdir");}
	}
	else{
		if($resftp->cwd($nextdir)){
			my $addr = ($year % 100) . $month . $day . "_" . $nextdir . "_RGB.jpg";
			if(my $tmp = $resftp->get($addr, "tmp\/$i.jpg")){
				$log->info("Download file $addr");
				push @files, $tmp;
			}
			else{$log->error("Can't download file $addr");}
			$resftp->cdup() or $log->error("Can't find prev directory");
		}
		else{$log->error("Can't find directory $nextdir");}	
	}
}
$ftp->quit;
$resftp->quit;

my $image = new Image::Magick;
foreach my $x (@files) {
	if($x){
		$image->Read($x);
		$log->info("Load file " . $x);
	}
}
$image->Contrast();

for (my $x = 0; $image->[$x]; $x++){
  	$image->[$x]->AdaptiveResize(width => $scale, height => $scale) if ($scale < 1080);
    $image->[$x]->Frame("$(scale)x$scale") if $image->[$x]->Get('magick') eq 'GIF';
    if($image->[$x]->Get('colors') == 1){
    	undef $image->[$x];
    	$log->warn("Image $x was dropped");
    }
    else{$log->info("Image $x was proccessed")}
}

$image->Write($outfile);

__END__

=head1 NAME

electro - program generates .gif file for curent date, using pictures from ElectroL satelite

=head1 SYNOPSIS

electro [options] <date>

Options:

	--out, -o 	  		- set output file

	--debug, -d	 		- set debug level

	--scale, -s 		- set result size 

	--help, -h 	 		- show this message

	date should be in ddmmyyyy format